# Generated by Django 5.2.8 on 2025-11-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuserscore',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='gameuserscore',
            unique_together=set(),
        ),
    ]
